name: dart_rut_validator
description: A small dart library to easily format, manipulate and validate chilean RUT.
version: 1.1.0
author: Eduardo Munoz <edomun@protonmail.com>
homepage: https://github.com/cgustav/dart_rut_validator

environment:
  sdk: ">=2.8.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

